add: profile duwik
wrideveloper/wrideveloper.github.io pull request #43
Opened 2023-11-12 16:00 UTC by Archin0

2023-11-13 01:44 UTC, elianiva requested changes
masukin subfolder dulu kek yg lain, cek di repo buat contoh

2023-11-13 06:54 UTC, elianiva requested changes
file yg ada di luar subfolder hapus aja

2023-11-13 08:44 UTC, Archin0 commented
wes mas :)

2023-11-15 05:37 UTC, elianiva approved these changes
LGTM

2023-11-15 05:37 UTC, merged